fig1:
	gcc -o fig1 -g -O2 -Iinclude lib/error.c -lpthread  fig_1.c
fig2:
	gcc -o fig2 -g -O2 -Iinclude lib/error.c -lpthread fig_2.c
fig3:
	gcc -o fig3 -g -O2 -Iinclude lib/error.c fig_3.c -lpthread
fig4:
	gcc -o fig4 -g -O2 -Iinclude lib/error.c  -lpthread fig_4.c
fig5:	
	gcc -o fig5 -g -O2 -Iinclude lib/error.c fig_5.c
fig6:	
	gcc -o fig6 -g -O2 -Iinclude lib/error.c fig_6.c
fig7:	
	gcc -o fig7 -g -O2 -Iinclude lib/error.c fig_7.c
fig8:	
	gcc -o fig8 -g -O2 -Iinclude lib/error.c fig_8.c
fig11:	
	gcc -o fig11 -g -O2 -Iinclude lib/error.c fig_11.c
fig12:	
	gcc -o fig12 -g -O2 -Iinclude lib/error.c fig_12.c
fig13:	
	gcc -o fig13 -g -O2 -Iinclude lib/error.c fig_13.c
fig14:	
	gcc -o fig14 -g -O2 -Iinclude lib/error.c fig_14.c
fig15:	
	gcc -o fig15 -g -O2 -Iinclude lib/error.c fig_15.c
fig16:	
	gcc -o fig16 -g -O2 -Iinclude lib/error.c fig_16.c
fig18:	
	gcc -o fig18 -g -O2 -Iinclude lib/error.c fig_18.c
