fig1:
	gcc -o fig1 -g -O2 -Iinclude lib/error.c  fig_1.c
fig2:
	gcc -o fig2 -g -O2 -Iinclude lib/error.c fig_2.c
fig3:
	gcc -o fig3 -g -O2 -Iinclude lib/error.c fig_3.c
fig4:
	gcc -o fig4 -g -O2 -Iinclude lib/error.c fig_4.c
fig5:	
	gcc -o fig5 -g -O2 -Iinclude lib/error.c fig_5.c
fig6:	
	gcc -o fig6 -g -O2 -Iinclude lib/error.c fig_6.c
fig7:	
	gcc -o fig7 -g -O2 -Iinclude lib/error.c lib/signal.c  fig_7.c
fig8:	
	gcc -o fig8 -g -O2 -Iinclude lib/error.c fig_8.c
fig16:	
	gcc -o fig16 -g -O2 -Iinclude lib/error.c fig_16.c
fig17:	
	gcc -o fig17 -g -O2 -Iinclude lib/error.c fig_17.c
fig18:	
	gcc -o fig18 -g -O2 -Iinclude lib/error.c fig_18.c
fork_Vfork_recource:	
	gcc -o fork_Vfork_recource -g -O2 -Iinclude lib/error.c lib/signal.c  fork_Vfork_recource.c
